apiVersion: apps/v1
kind: Deployment
metadata:
  name: imh-recipe
  labels:
    app: imh-recipe
spec:
  selector:
    matchLabels:
      app: imh-recipe
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: imh-recipe
    spec:
      containers:
      - image: towatech2020/imh-recipe
        imagePullPolicy: Always
        name: imh-recipe
        ports:
        - containerPort: 3002
