apiVersion: v1
kind: Service
metadata:
  name: imh-ui-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: imh-ui
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      xForwarededFor: true
      timeoutSeconds: 5

